# Use the § symbol for color coding
# Use %name for the name of the player who did /vanish
#   Default Config:
#     FakeLeave-message: "§e%name Left the game"
#     FakeJoin-message: "§e%name joined the game"

# Do not change this!
config-version: 2

# The message that will be sent to online players when you turn on your vanish
enable-leave: false
FakeLeave-message: "§e%name left the game"

# The message that will be sent to online players when you turn off your vanish
enable-join: false
FakeJoin-message: "§e%name joined the game"

# Choose if the player should be unvanished when he leave the server
unvanish-after-leaving: false

# Choose if vanished players can fly when they are in survival
enable-fly: true

# Choose if vanished players can take damage when they are in survival mode
disable-damage: true

# Choose if chest should be silent when you open them (Chests will be read-only)
silent-chest: true

# Choose if vanished players should lose hunger
hunger: false
...
